shell script

diff --git a/10-install-script b/10-install-script
--- a/10-install-script
+++ b/10-install-script
@@ -8,22 +8,43 @@ then
     exit 1
  fi
 
- dnf install mysql -y
+ dnf list installed mysql
 
  if [ $? -ne 0 ]
- then
-    echo " Installing MySQL ... FAILURE"
-    exit 1
- else
-    echo "Installing MYSQL ... SUCCESS"
- fi    
+ then 
+     dnf install mysql -y
+    if [ $? -ne 0 ]
+    then
+        echo " Installing MySQL ... FAILURE"
+        exit 1
+    else
+        echo "Installing MYSQL ... SUCCESS"
+    fi 
+else 
+    echo " MySQL is already .... INSTALLED"
+fi    
 
- dnf install git -y
+    # if [ $? -ne 0 ]
+    # then
+    #     echo "Installing MySQL ... FAILURE"
+    #     exit 1
+    # else
+    #     echo "Installing MySQL ... SUCCESS"
+    # fi 
 
- if [ $? -ne 0 ]
+    dnf list installed git
+
+    if [ $? -ne 0 ]
+    then 
+    dnf install git -y
+    if [ $? -ne 0 ]  
  then
-    echo " Installing Git ... FAILURE"
-    exit 1
+        echo " Installing git ... FAILURE"
+        exit 1
  else
-    echo "Installing Git ... SUCCESS"
- fi  
+        echo "Installing git ... SUCCESS"
+    fi  
+ else  
+     echo " git is already .... INSTALLED"     
+  fi    
+ 
