shell script

diff --git a/10-install-script b/10-install-script
--- a/10-install-script
+++ b/10-install-script
@@ -10,4 +10,20 @@ then
 
  dnf install mysqll -y
 
- dnf install git -y   
+ if [ $? -ne 0 ]
+ then
+    echo " Installing MySQL ... FAILURE"
+    exit 1
+ else
+    echo "Installing MYSQL ... SUCCESS"
+ fi    
+
+ dnf install git -y
+
+ if [ $? -ne 0 ]
+ then
+    echo " Installing Git ... FAILURE"
+    exit 1
+ else
+    echo "Installing Git ... SUCCESS"
+ fi  
